spring:
  application:
    name: HOTEL-SERVICE
  config:
    import: optional:configserver://localhost:8086

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka




